version: 2
jobs:
  build-and-test:
    docker:
      - image: circleci/node:6.12.3-browsers
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test

  safari:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: grunt build retire testconfig fixture connect test-webdriver:safari

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-and-test
      - safari
